# Generated by Django 5.2.16 on 2026-07-20 12:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='メールアドレス')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '担当者',
                'verbose_name_plural': '担当者',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RosterMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='年')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='月')),
                ('status', models.CharField(choices=[('draft', '準備中'), ('generated', '生成済み'), ('confirmed', '確定')], default='draft', max_length=20, verbose_name='状態')),
                ('generation_version', models.PositiveIntegerField(default=0, verbose_name='生成バージョン')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='確定日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '月別当直表',
                'verbose_name_plural': '月別当直表',
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='unique_roster_month')],
            },
        ),
        migrations.CreateModel(
            name='CalendarDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_date', models.DateField(verbose_name='日付')),
                ('is_holiday', models.BooleanField(default=False, verbose_name='休日・祝日')),
                ('holiday_name', models.CharField(blank=True, max_length=100, verbose_name='休日名')),
                ('holiday_source', models.CharField(choices=[('weekend', '土日'), ('national', '祝日'), ('custom', '独自休日'), ('override', '手動設定'), ('weekday', '平日')], default='weekday', max_length=20, verbose_name='休日区分')),
                ('roster_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='roster.rostermonth')),
            ],
            options={
                'verbose_name': 'カレンダー日',
                'verbose_name_plural': 'カレンダー日',
                'ordering': ['duty_date'],
            },
        ),
        migrations.CreateModel(
            name='DutyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_type', models.CharField(choices=[('day', '日直'), ('night', '夜間当直')], max_length=20, verbose_name='当直種別')),
                ('is_manual', models.BooleanField(default=False, verbose_name='手動変更')),
                ('generation_version', models.PositiveIntegerField(default=1, verbose_name='生成バージョン')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='roster.calendarday')),
                ('roster_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='roster.rostermonth')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='roster.staffmember')),
            ],
            options={
                'verbose_name': '当直割り当て',
                'verbose_name_plural': '当直割り当て',
                'ordering': ['calendar_day__duty_date', 'duty_type'],
            },
        ),
        migrations.CreateModel(
            name='UnavailableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_type', models.CharField(choices=[('day', '日直'), ('night', '夜間当直')], max_length=20, verbose_name='当直種別')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_slots', to='roster.calendarday')),
                ('roster_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_slots', to='roster.rostermonth')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unavailable_slots', to='roster.staffmember')),
            ],
            options={
                'verbose_name': '希望しない当直枠',
                'verbose_name_plural': '希望しない当直枠',
            },
        ),
        migrations.AddConstraint(
            model_name='calendarday',
            constraint=models.UniqueConstraint(fields=('roster_month', 'duty_date'), name='unique_calendar_day'),
        ),
        migrations.AddConstraint(
            model_name='dutyassignment',
            constraint=models.UniqueConstraint(fields=('calendar_day', 'duty_type'), name='unique_duty_assignment'),
        ),
        migrations.AddConstraint(
            model_name='unavailableslot',
            constraint=models.UniqueConstraint(fields=('calendar_day', 'staff_member', 'duty_type'), name='unique_unavailable_slot'),
        ),
    ]
