# Generated by Django 5.2.16 on 2026-07-20 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmember',
            name='email',
        ),
        migrations.AddField(
            model_name='staffmember',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='削除済み'),
        ),
        migrations.CreateModel(
            name='MonthlyStaffSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='月間担当回数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roster_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_settings', to='roster.rostermonth')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_settings', to='roster.staffmember')),
            ],
            options={
                'verbose_name': '月間担当回数設定',
                'verbose_name_plural': '月間担当回数設定',
                'constraints': [models.UniqueConstraint(fields=('roster_month', 'staff_member'), name='unique_monthly_staff_setting')],
            },
        ),
    ]
