# Generated by Django 5.2.16 on 2026-07-25 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_remove_staffmember_email_staffmember_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutySlotSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_type', models.CharField(choices=[('day', '日直'), ('night', '夜間当直')], max_length=20, verbose_name='当直種別')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='割り当てる')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_slot_settings', to='roster.calendarday')),
                ('roster_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_slot_settings', to='roster.rostermonth')),
            ],
            options={
                'verbose_name': '担当日設定',
                'verbose_name_plural': '担当日設定',
                'constraints': [models.UniqueConstraint(fields=('calendar_day', 'duty_type'), name='unique_duty_slot_setting')],
            },
        ),
    ]
